# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Serafeim
tagline:          ''
description:      'DevOps Engineer'
baseurl:          ''

author:
  name:           'Serafeim'
  url:            'serafeimgr.github.io'
  email:          'serafeimgr@gmail.com'
  github:         'https://github.com/serafeimgr'
  reddit:         ''

paginate:         2

# Custom vars
github:
  repo:           https://github.com/serafeimgr

jekyll_analytics:
  GoogleAnalytics:
    id: UA-172414184-1

plugins: [jekyll-gist, jekyll-paginate, jekyll-analytics]