# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Serafeim Tgrds
tagline:          ''
description:      'Software Developer | Continuous Integration Engineer'
baseurl:          

author:
  name:           'Serafeim Tgrds'
  url:            'serafeimgr.github.io'
  email:          'serafeimgr@gmail.com'
  github:         'https://github.com/serafeimgr'
  twitter:        ''
  googleplus:     ''
  linkedin:       ''


paginate:         3

# Custom vars
github:
  repo:           https://github.com/serafeimgr

gems: [jekyll-gist, jekyll-paginate]
