# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Serafeim
tagline:          ''
description:      'DevOps Engineer'
baseurl:          ''
url:              https://serafeim.io

author:
  name:           'Serafeim'
  url:            'serafeimgr.github.io'
  email:          'serafeimgr@gmail.com'
  github:         'https://github.com/serafeimgr'
  reddit:         ''

paginate:         1
paginate_path:    "page:num"

# Custom vars
github:
  repo:           https://github.com/serafeimgr

plugins: [jekyll-gist, jekyll-paginate]